name: openthesaurus
description: A small dart library for querying synonyms from openthesaurus.de
version: 0.0.3
repository: https://github.com/hayribakici/openthesaurus-dart

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  json_annotation: ^4.8.1
  http: ^0.13.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.0.3
  json_serializable: any
